//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DusMLM
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_task
    {
        public string job_taskid { get; set; }
        public string job_name { get; set; }
        public string job_desc { get; set; }
        public Nullable<System.DateTime> job_dateline { get; set; }
        public Nullable<decimal> job_targetqty { get; set; }
        public Nullable<decimal> job_realqty { get; set; }
        public Nullable<double> job_value { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
