//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DusMLM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jobtaskappEntities : DbContext
    {
        public jobtaskappEntities()
            : base("name=jobtaskappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<job_task> job_task { get; set; }
        public virtual DbSet<user_member> user_member { get; set; }
        public virtual DbSet<V_Sisa_Job_Fee> V_Sisa_Job_Fee { get; set; }
        public virtual DbSet<V_Sisa_Job_Target_Qty> V_Sisa_Job_Target_Qty { get; set; }
        public virtual DbSet<V_user_id_level1> V_user_id_level1 { get; set; }
        public virtual DbSet<trjob> trjobs { get; set; }
        public virtual DbSet<V_Sisa_Job_Valid_Qty> V_Sisa_Job_Valid_Qty { get; set; }
        public virtual DbSet<V_Fee_Per_User_Job> V_Fee_Per_User_Job { get; set; }
        public virtual DbSet<trpayment> trpayments { get; set; }
        public virtual DbSet<V_Fee_Per_User> V_Fee_Per_User { get; set; }
    
        public virtual int ADD_JOB_TASK(string job_name, string job_desc, Nullable<System.DateTime> job_dateline, Nullable<decimal> job_targetqty, Nullable<double> job_value, string user_login)
        {
            var job_nameParameter = job_name != null ?
                new ObjectParameter("job_name", job_name) :
                new ObjectParameter("job_name", typeof(string));
    
            var job_descParameter = job_desc != null ?
                new ObjectParameter("job_desc", job_desc) :
                new ObjectParameter("job_desc", typeof(string));
    
            var job_datelineParameter = job_dateline.HasValue ?
                new ObjectParameter("job_dateline", job_dateline) :
                new ObjectParameter("job_dateline", typeof(System.DateTime));
    
            var job_targetqtyParameter = job_targetqty.HasValue ?
                new ObjectParameter("job_targetqty", job_targetqty) :
                new ObjectParameter("job_targetqty", typeof(decimal));
    
            var job_valueParameter = job_value.HasValue ?
                new ObjectParameter("job_value", job_value) :
                new ObjectParameter("job_value", typeof(double));
    
            var user_loginParameter = user_login != null ?
                new ObjectParameter("user_login", user_login) :
                new ObjectParameter("user_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_JOB_TASK", job_nameParameter, job_descParameter, job_datelineParameter, job_targetqtyParameter, job_valueParameter, user_loginParameter);
        }
    
        public virtual int ADD_TRFEE(string trfee_job_taskid, Nullable<int> trfee_user_level, Nullable<double> trfee_job_value)
        {
            var trfee_job_taskidParameter = trfee_job_taskid != null ?
                new ObjectParameter("trfee_job_taskid", trfee_job_taskid) :
                new ObjectParameter("trfee_job_taskid", typeof(string));
    
            var trfee_user_levelParameter = trfee_user_level.HasValue ?
                new ObjectParameter("trfee_user_level", trfee_user_level) :
                new ObjectParameter("trfee_user_level", typeof(int));
    
            var trfee_job_valueParameter = trfee_job_value.HasValue ?
                new ObjectParameter("trfee_job_value", trfee_job_value) :
                new ObjectParameter("trfee_job_value", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TRFEE", trfee_job_taskidParameter, trfee_user_levelParameter, trfee_job_valueParameter);
        }
    
        public virtual int ADD_TRJOB(string trjob_job_taskid, string trjob_user_id_level1, Nullable<decimal> trjob_target_qty)
        {
            var trjob_job_taskidParameter = trjob_job_taskid != null ?
                new ObjectParameter("trjob_job_taskid", trjob_job_taskid) :
                new ObjectParameter("trjob_job_taskid", typeof(string));
    
            var trjob_user_id_level1Parameter = trjob_user_id_level1 != null ?
                new ObjectParameter("trjob_user_id_level1", trjob_user_id_level1) :
                new ObjectParameter("trjob_user_id_level1", typeof(string));
    
            var trjob_target_qtyParameter = trjob_target_qty.HasValue ?
                new ObjectParameter("trjob_target_qty", trjob_target_qty) :
                new ObjectParameter("trjob_target_qty", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TRJOB", trjob_job_taskidParameter, trjob_user_id_level1Parameter, trjob_target_qtyParameter);
        }
    
        public virtual int ADD_TRRESULT_WI_VALIDATION(string trresult_job_taskid, string trresult_user_id, Nullable<decimal> trresult_resultqty, Nullable<decimal> trresult_validqty, string trresult_user_login)
        {
            var trresult_job_taskidParameter = trresult_job_taskid != null ?
                new ObjectParameter("trresult_job_taskid", trresult_job_taskid) :
                new ObjectParameter("trresult_job_taskid", typeof(string));
    
            var trresult_user_idParameter = trresult_user_id != null ?
                new ObjectParameter("trresult_user_id", trresult_user_id) :
                new ObjectParameter("trresult_user_id", typeof(string));
    
            var trresult_resultqtyParameter = trresult_resultqty.HasValue ?
                new ObjectParameter("trresult_resultqty", trresult_resultqty) :
                new ObjectParameter("trresult_resultqty", typeof(decimal));
    
            var trresult_validqtyParameter = trresult_validqty.HasValue ?
                new ObjectParameter("trresult_validqty", trresult_validqty) :
                new ObjectParameter("trresult_validqty", typeof(decimal));
    
            var trresult_user_loginParameter = trresult_user_login != null ?
                new ObjectParameter("trresult_user_login", trresult_user_login) :
                new ObjectParameter("trresult_user_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TRRESULT_WI_VALIDATION", trresult_job_taskidParameter, trresult_user_idParameter, trresult_resultqtyParameter, trresult_validqtyParameter, trresult_user_loginParameter);
        }
    
        public virtual int ADD_TRRESULT_WO_VALIDATION(string trresult_job_taskid, string trresult_user_id, Nullable<decimal> trresult_resultqty, string trresult_user_login)
        {
            var trresult_job_taskidParameter = trresult_job_taskid != null ?
                new ObjectParameter("trresult_job_taskid", trresult_job_taskid) :
                new ObjectParameter("trresult_job_taskid", typeof(string));
    
            var trresult_user_idParameter = trresult_user_id != null ?
                new ObjectParameter("trresult_user_id", trresult_user_id) :
                new ObjectParameter("trresult_user_id", typeof(string));
    
            var trresult_resultqtyParameter = trresult_resultqty.HasValue ?
                new ObjectParameter("trresult_resultqty", trresult_resultqty) :
                new ObjectParameter("trresult_resultqty", typeof(decimal));
    
            var trresult_user_loginParameter = trresult_user_login != null ?
                new ObjectParameter("trresult_user_login", trresult_user_login) :
                new ObjectParameter("trresult_user_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TRRESULT_WO_VALIDATION", trresult_job_taskidParameter, trresult_user_idParameter, trresult_resultqtyParameter, trresult_user_loginParameter);
        }
    
        public virtual int ADD_USER_MEMBER(string user_id, string user_password, string user_name, string user_upline, string user_login)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var user_uplineParameter = user_upline != null ?
                new ObjectParameter("user_upline", user_upline) :
                new ObjectParameter("user_upline", typeof(string));
    
            var user_loginParameter = user_login != null ?
                new ObjectParameter("user_login", user_login) :
                new ObjectParameter("user_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_USER_MEMBER", user_idParameter, user_passwordParameter, user_nameParameter, user_uplineParameter, user_loginParameter);
        }
    
        public virtual int UPDATE_TRRESULT_VALIDATION(string trresult_job_taskid, string trresult_user_id, Nullable<decimal> trresult_resultqty, Nullable<decimal> trresult_validqty, string trresult_user_login, Nullable<System.DateTime> trresult_created_date)
        {
            var trresult_job_taskidParameter = trresult_job_taskid != null ?
                new ObjectParameter("trresult_job_taskid", trresult_job_taskid) :
                new ObjectParameter("trresult_job_taskid", typeof(string));
    
            var trresult_user_idParameter = trresult_user_id != null ?
                new ObjectParameter("trresult_user_id", trresult_user_id) :
                new ObjectParameter("trresult_user_id", typeof(string));
    
            var trresult_resultqtyParameter = trresult_resultqty.HasValue ?
                new ObjectParameter("trresult_resultqty", trresult_resultqty) :
                new ObjectParameter("trresult_resultqty", typeof(decimal));
    
            var trresult_validqtyParameter = trresult_validqty.HasValue ?
                new ObjectParameter("trresult_validqty", trresult_validqty) :
                new ObjectParameter("trresult_validqty", typeof(decimal));
    
            var trresult_user_loginParameter = trresult_user_login != null ?
                new ObjectParameter("trresult_user_login", trresult_user_login) :
                new ObjectParameter("trresult_user_login", typeof(string));
    
            var trresult_created_dateParameter = trresult_created_date.HasValue ?
                new ObjectParameter("trresult_created_date", trresult_created_date) :
                new ObjectParameter("trresult_created_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_TRRESULT_VALIDATION", trresult_job_taskidParameter, trresult_user_idParameter, trresult_resultqtyParameter, trresult_validqtyParameter, trresult_user_loginParameter, trresult_created_dateParameter);
        }
    
        public virtual int ADD_TRDELIVER(string trdeliver_job_taskid, string trdeliver_user_id_level1, Nullable<decimal> trtrdeliver_deliverqty, string trtrdeliver_login)
        {
            var trdeliver_job_taskidParameter = trdeliver_job_taskid != null ?
                new ObjectParameter("trdeliver_job_taskid", trdeliver_job_taskid) :
                new ObjectParameter("trdeliver_job_taskid", typeof(string));
    
            var trdeliver_user_id_level1Parameter = trdeliver_user_id_level1 != null ?
                new ObjectParameter("trdeliver_user_id_level1", trdeliver_user_id_level1) :
                new ObjectParameter("trdeliver_user_id_level1", typeof(string));
    
            var trtrdeliver_deliverqtyParameter = trtrdeliver_deliverqty.HasValue ?
                new ObjectParameter("trtrdeliver_deliverqty", trtrdeliver_deliverqty) :
                new ObjectParameter("trtrdeliver_deliverqty", typeof(decimal));
    
            var trtrdeliver_loginParameter = trtrdeliver_login != null ?
                new ObjectParameter("trtrdeliver_login", trtrdeliver_login) :
                new ObjectParameter("trtrdeliver_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TRDELIVER", trdeliver_job_taskidParameter, trdeliver_user_id_level1Parameter, trtrdeliver_deliverqtyParameter, trtrdeliver_loginParameter);
        }
    
        public virtual int ADD_TRPAYMENT(string trpayment_job_taskid, string trpayment_user_id_upline, string trpayment_user_id, Nullable<double> trpayment_debet, Nullable<double> trpayment_credit, string trpayment_login)
        {
            var trpayment_job_taskidParameter = trpayment_job_taskid != null ?
                new ObjectParameter("trpayment_job_taskid", trpayment_job_taskid) :
                new ObjectParameter("trpayment_job_taskid", typeof(string));
    
            var trpayment_user_id_uplineParameter = trpayment_user_id_upline != null ?
                new ObjectParameter("trpayment_user_id_upline", trpayment_user_id_upline) :
                new ObjectParameter("trpayment_user_id_upline", typeof(string));
    
            var trpayment_user_idParameter = trpayment_user_id != null ?
                new ObjectParameter("trpayment_user_id", trpayment_user_id) :
                new ObjectParameter("trpayment_user_id", typeof(string));
    
            var trpayment_debetParameter = trpayment_debet.HasValue ?
                new ObjectParameter("trpayment_debet", trpayment_debet) :
                new ObjectParameter("trpayment_debet", typeof(double));
    
            var trpayment_creditParameter = trpayment_credit.HasValue ?
                new ObjectParameter("trpayment_credit", trpayment_credit) :
                new ObjectParameter("trpayment_credit", typeof(double));
    
            var trpayment_loginParameter = trpayment_login != null ?
                new ObjectParameter("trpayment_login", trpayment_login) :
                new ObjectParameter("trpayment_login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TRPAYMENT", trpayment_job_taskidParameter, trpayment_user_id_uplineParameter, trpayment_user_idParameter, trpayment_debetParameter, trpayment_creditParameter, trpayment_loginParameter);
        }
    }
}
