//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DusMLM
{
    using System;
    using System.Collections.Generic;
    
    public partial class trjob
    {
        public int id { get; set; }
        public string trjob_job_taskid { get; set; }
        public string trjob_user_id_level1 { get; set; }
        public Nullable<decimal> trjob_targetqty { get; set; }
        public Nullable<decimal> trjob_realqty { get; set; }
        public Nullable<decimal> trjob_validqty { get; set; }
    }
}
