//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DusMLM
{
    using System;
    using System.Collections.Generic;
    
    public partial class trpayment
    {
        public int id { get; set; }
        public string trpayment_job_taskid { get; set; }
        public string trpayment_user_id_upline { get; set; }
        public string trpayment_user_id { get; set; }
        public Nullable<double> trpayment_debet { get; set; }
        public Nullable<double> trpayment_credit { get; set; }
        public Nullable<System.DateTime> trpayment_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
