//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DusMLM
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_member
    {
        public string user_id { get; set; }
        public string user_password { get; set; }
        public string user_name { get; set; }
        public string user_upline { get; set; }
        public string user_jaringan { get; set; }
        public Nullable<int> user_level { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> active_status { get; set; }
        public string user_upline_level1 { get; set; }
    }
}
