//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DusMLM
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Fee_Per_User_Job
    {
        public string trpayment_user_id { get; set; }
        public Nullable<double> Total_Fee { get; set; }
        public Nullable<double> Total_Fee_Terbayar { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string job_taskid { get; set; }
        public string job_name { get; set; }
        public string job_desc { get; set; }
        public Nullable<int> status { get; set; }
    }
}
